<!DOCTYPE html><html lang="en"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width, initial-scale=1"> <meta name="description" content=""> <meta name="author" content=""><title>FCUL</title><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"><style type="text/css">/* Sticky footer styles-------------------------------------------------- */html{position: relative; min-height: 100%;}body{/* Margin bottom by footer height */ margin-bottom: 60px;}.footer{position: absolute; bottom: 0; width: 100%; /* Set the fixed height of the footer here */ height: 60px; background-color: #f5f5f5;}/* Custom page CSS-------------------------------------------------- *//* Not required for template or sticky footer method. */body > .container{padding: 60px 15px 0;}.container .text-muted{margin: 20px 0;}.footer > .container{padding-right: 15px; padding-left: 15px;}.navbar{background-image: url("http://www.fc.ul.pt/sites/all/themes/fcul/img/header_bg.png"); repeat-x scroll 0 0; height: 100px;padding-top: 15px;}</style><!-- Custom styles for this template - <link href="sticky-footer-navbar.css" rel="stylesheet">--><!--[if lt IE 9]> <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script> <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]--> </head> <body> <nav class="navbar navbar-default navbar-fixed-top"> <div class="container"><img src="http://www.fc.ul.pt/sites/all/themes/fcul/img/logo.png" alt="FCUL"/> </div></nav> <div class="container"> 
<div class="page-header" style="border-bottom: 0px solid #EEE;"> <!--
<p>&nbsp;</p><h1>Alguma coisa não correu como era esperado!</h1> 
-->
</div><!--
<p class="lead">Isto pode ter ocorrido por vários motivos:</p><ol> <li>A página está temporariamente desactivada</li><li>A página mudou de nome ou de endereço</li><li>O link está errado</li><li>O endereço está errado</li><li>A página deixou de existir</li></ol> <p><a href="javascript:history.back();">Voltar</a> à pagina anterior</p>
-->
<?php echo $this->fetch('content'); ?>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script></body></html>